"""Immutable value object encapsulating the 5-axis AI score generated by the OpenAI engine."""

from dataclasses import dataclass


@dataclass(frozen=True)
class AIScore:
    total: float
    academic_training: float  # Academic degrees: PhD, Master's, certifications
    experience: float  # University teaching experience in years
    publications: float  # Scopus/indexed papers and R&D projects
    profile_match: float  # Alignment with the target vacancy requirements
    languages_competencies: float  # English proficiency and specialized digital tools
    evaluation_summary: str  # AI-generated summary, max 200 characters

    def __post_init__(self) -> None:
        axes_to_validate = {
            "total": self.total,
            "academic_training": self.academic_training,
            "experience": self.experience,
            "publications": self.publications,
            "profile_match": self.profile_match,
            "languages_competencies": self.languages_competencies,
        }
        for name, value in axes_to_validate.items():
            if not (0.0 <= value <= 100.0):
                raise ValueError(f"AIScore.{name} must be between 0.0 and 100.0, got {value}")
        if len(self.evaluation_summary) > 200:
            raise ValueError(
                f"evaluation_summary exceeds 200 characters: {len(self.evaluation_summary)}"
            )

    @property
    def is_preselected(self) -> bool:
        return self.total >= 60.0

    @property
    def grade(self) -> str:
        if self.total >= 85:
            return "EXCELLENT"
        elif self.total >= 70:
            return "GOOD"
        elif self.total >= 60:
            return "ACCEPTABLE"
        else:
            return "INSUFFICIENT"
