"""add_error_reason_to_applications

Revision ID: a0e3b37edc40
Revises: c09a9c2412a8
Create Date: 2026-06-25 05:58:15.112750+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0e3b37edc40'
down_revision: Union[str, None] = 'c09a9c2412a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('error_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'error_reason')
    # ### end Alembic commands ###
